// signup
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const ALREADY_REGISTERED = "ALREADY_REGISTERED";
export const TOKEN_RESET = "TOKEN_RESET";

// verification
export const VERIFICATION_RESET = "VERIFICATION_RESET";
export const VERIFICATION_PENDING = "VERIFICATION_PENDING";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FAIL = "VERIFICATION_FAIL";

// photos
export const FACE_PHOTO_CAPTURED = "FACE_PHOTO_CAPTURED";
export const DOC_PHOTO_CAPTURED = "DOC_PHOTO_CAPTURED";
export const DOC_PHOTO_RESET = "DOC_PHOTO_RESET";
export const FACE_PHOTO_RESET = "FACE_PHOTO_RESET";
